spring.application.name: test-service

eureka: 
  instance:
    prefer-ip-address: true
    nonSecurePort: ${server.port:9031}
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
     defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
     #defaultZone:http://localhost:8761/eureka/
      
server.port: 8090